### ISSUE TITLE
minis standalone has error when attempting to detect events

### ISSUE THREAD

**Issue by Madeleine36** [dervinism/minis#1] opened 2022-05-10 15:03 UTC
When trying to use the minis standalone to detect events in a file, it has an error. The window asking to band stop filter comes up, and then the system has an error regardless of whether you choose yes or no. The bottom of the screen says "State: Execution failed. See minisLogFile inside the working directory." 

If I use an ABF 2.00 file, the log file says: 
Detection task initiated
Program execution failed
Reference to non-existent field 'nADCSamplingSeq'.
Error in loadABF
Error in detectMinisStandalone
Error in minis
Error in gui_mainfcn (line 95)
Error in minis
Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)minis('startTool_ClickedCallback',hObject,eventdata,guidata(hObject))
Error using waitforallfiguresclosed (line 14)
Error while evaluating PushTool ClickedCallback.

If I use an ABF 1.8 integral file, the log file says "Index in position 2 exceeds array bounds." instead of "Reference to non-existent field 'nADCSamplingSeq'."

Is there a specific file format needed or a way to add support for these files?
Any help is appreciated!

**Comment by dervinism** [comment] 2022-05-11 11:15
The software does not work with version 2 ABF files, only with version 1.8. The error was caused by single channel ABF files. I have now fixed the issue and the software whould be able to deal with single channel abf files.

**Closed as completed by dervinism** 2022-05-11 11:15 UTC
